openapi: 3.0.0
info:
  title: 'Test API Must Informatique'
  description: 'This is a test API from Aurélien Soulard for Must Informatique'
  version: '0.1'
tags:
  - name: Admin
    description: "Admin API to manage users (limited to local access)"
  - name: Authentication
    description: "Login and logout for Store API (public access)"
  - name: Store/Brands
    description: "Store API to manage brands (public access)"
  - name: Store/Categories
    description: "Store API to manage product categories (public access)"
components:
  schemas:
    NewUser:
      type: object
      properties:
        userName:
          type: string
          maxLength: 25
        login:
          type: string
          maxLength: 25
        password:
          type: string
          maxLength: 25
    User:
      type: object
      properties:
        id:
          type: integer
        userName:
          type: string
        login:
          type: string
    UserLogin:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
    Brand:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
paths:
  /admin/users:
    get:
      tags:
        - Admin
      description: 'Return all existing users'
      operationId: 'App\Controller\Admin\UserController::getAllAction'
      produces:
        - application/json
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags:
        - Admin
      description: 'Create a user and returns it'
      operationId: 'App\Controller\Admin\UserController::createAction'
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        description: A JSON object containing user information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad parameters
  /admin/users/{userId}:
    delete:
      tags:
        - Admin
      description: 'Delete a user'
      operationId: 'App\Controller\Admin\UserController::deleteAction'
      produces:
        - application/json
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: User id to delete
      responses:
        '204':
          description: User deleted
        '404':
          description: User not found
  /login:
    post:
      tags:
        - Authentication
      description: 'Login and get authentication token'
      operationId: 'App\Controller\Authentication\AuthenticationController::loginAction'
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        description: A JSON object containing user login and password
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                properties:
                  token:
                    type: string
        '401':
          description: Authentication failed
  /logout:
    get:
      tags:
        - Authentication
      description: 'Logout a user and delete his token'
      operationId: 'App\Controller\Authentication\AuthenticationController::logoutAction'
      produces:
        - application/json
      parameters:
        - in: header
          name: MUST-API-TOKEN
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Logout successful
  /store/brands:
    get:
      tags:
        - Store/Brands
      description: 'Return all existing brands'
      operationId: 'App\Controller\Store\BrandController::getAllAction'
      parameters:
        - in: header
          name: MUST-API-TOKEN
          schema:
            type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Brand'
        '401':
          description: Unauthorized Access
    post:
      tags:
        - Store/Brands
      description: 'Create a brand'
      operationId: 'App\Controller\Store\BrandController::createAction'
      parameters:
        - in: header
          name: MUST-API-TOKEN
          schema:
            type: string
          required: true
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        description: A JSON object containing the new brand information
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Brand created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Brand'
        '401':
          description: Authentication failed
  /store/brands/{brandId}:
    put:
      tags:
        - Store/Brands
      description: 'Update a brand'
      operationId: 'App\Controller\Store\BrandController::editAction'
      parameters:
        - in: path
          name: brandId
          schema:
            type: integer
          required: true
          description: Brand id to update
        - in: header
          name: MUST-API-TOKEN
          schema:
            type: string
          required: true
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        description: A JSON object containing the brand information
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Brand updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Brand'
        '404':
          description: Brand not found
        '401':
          description: Authentication failed
    delete:
      tags:
        - Store/Brands
      description: 'Delete a brand'
      operationId: 'App\Controller\Store\BrandController::deleteAction'
      produces:
        - application/json
      parameters:
        - in: path
          name: brandId
          schema:
            type: integer
          required: true
          description: Brand id to delete
        - in: header
          name: MUST-API-TOKEN
          schema:
            type: string
          required: true
      responses:
        '204':
          description: Brand deleted
        '404':
          description: Brand not found
        '401':
          description: Authentication failed
  /store/categories:
    get:
      tags:
        - Store/Categories
      description: 'Return all existing product categories'
      operationId: 'App\Controller\Store\CategoryController::getAllAction'
      parameters:
        - in: header
          name: MUST-API-TOKEN
          schema:
            type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '401':
          description: Unauthorized Access
    post:
      tags:
        - Store/Categories
      description: 'Create a product category'
      operationId: 'App\Controller\Store\CategoryController::createAction'
      parameters:
        - in: header
          name: MUST-API-TOKEN
          schema:
            type: string
          required: true
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        description: A JSON object containing the new category information
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Category created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '401':
          description: Authentication failed
  /store/categories/{categoryId}:
    put:
      tags:
        - Store/Categories
      description: 'Update a category'
      operationId: 'App\Controller\Store\CategoryController::editAction'
      parameters:
        - in: path
          name: categoryId
          schema:
            type: integer
          required: true
          description: Category id to update
        - in: header
          name: MUST-API-TOKEN
          schema:
            type: string
          required: true
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        description: A JSON object containing the category information
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Category updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: Category not found
        '401':
          description: Authentication failed
    delete:
      tags:
        - Store/Categories
      description: 'Delete a category'
      operationId: 'App\Controller\Store\CategoryController::deleteAction'
      produces:
        - application/json
      parameters:
        - in: path
          name: categoryId
          schema:
            type: integer
          required: true
          description: Category id to delete
        - in: header
          name: MUST-API-TOKEN
          schema:
            type: string
          required: true
      responses:
        '204':
          description: Category deleted
        '404':
          description: Category not found
        '401':
          description: Authentication failed
